In [3]:
import pandas as pd
data=pd.Series([10,20,30,40])
print(data)

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
data=pd.Series([10,20,30],index=["x","y","z"])
print(data)

x    10
y    20
z    30
dtype: int64

In [7]:
data={
    "Name":["Ram","Vani"],
    "Age":[20,25]
}

df=pd.DataFrame(data)
print(df)
print("\n")

print(df.loc[0])

   Name  Age
0   Ram   20
1  Vani   25


Name    Ram
Age      20
Name: 0, dtype: object

In [11]:
df=pd.read_csv("Untitled spreadsheet - Sheet1.csv")
print(df)

      NAME CLASS  MARKS
0  SHRIHAN   BCA     89
1   BHUVAN  MBBS     90
2     RITU  BTEC     87

In [12]:
df.isnull()

    NAME  CLASS  MARKS
0  False  False  False
1  False  False  False
2  False  False  False

In [13]:
df.dropna

<bound method DataFrame.dropna of       NAME CLASS  MARKS
0  SHRIHAN   BCA     89
1   BHUVAN  MBBS     90
2     RITU  BTEC     87>

In [14]:
df.fillna(0)

      NAME CLASS  MARKS
0  SHRIHAN   BCA     89
1   BHUVAN  MBBS     90
2     RITU  BTEC     87

In [17]:
print(df["MARKS"].mean())
print(df.MARKS.sum())
print(df.MARKS.min())
print(df.MARKS.max())
print(df.MARKS.count())

88.66666666666667
266
87
90
3

In [26]:
print(df.shape)
print(df.ndim)
print(len(df))
print(df.head(1))
print(df.tail(1))

print(df.index)
print(df.columns)

(4, 3)
2
4
   ID   Name  Marks
0   1  Rahul     85
   ID  Name  Marks
3   4  Sara     92
RangeIndex(start=0, stop=4, step=1)
Index(['ID', 'Name', 'Marks'], dtype='object')

In [22]:
import pandas as pd

data={
    "ID":[1,2,3,4],
    "Name":["Rahul","Priya","Amit","Sara"],
    "Marks":[85,90,78,92]
}
df=pd.DataFrame(data)

df=pd.DataFrame(data)

df.to_csv("Students.csv",index=False)
print("CSV file creates successfully")

CSV file creates successfully